### PR TITLE
Minor tweaks

### PR DESCRIPTION
**Pull request by lsmith77**
the important commit is the 2nd one, which fixes a BC break in PHPCR ODM. so feel free to either merge the entire PR .. or just cherry pick c83168f

### CODE REVIEW

**Comment by lsmith77** [comment]
btw .. you guys should enable travis ci for the tests .. there was a test that should have picked up this BC break in PHPCR ODM.

**Comment by hacfi** [comment]
Thanks for the quick fix!

**Comment by hacfi** [comment]
There are two more occurrences of the exception:
https://github.com/lsmith77/KnowledgeBase/blob/c83168fff36e13b4bc1d29d79b120e0b5c8246df/src/ServerGrove/KbBundle/Controller/Admin/UrlsController.php#L147
https://github.com/lsmith77/KnowledgeBase/blob/c83168fff36e13b4bc1d29d79b120e0b5c8246df/src/ServerGrove/KbBundle/Controller/Admin/UrlsController.php#L182

**Comment by lsmith77** [comment]
thx .. fixed too

**Comment by iambrosi** [comment]
Merged. Thank you!

**Pull request merged**
